
spring:
  application:
    name: msservicerh
  datasource:
    url: jdbc:postgresql://localhost:5432/gerenciador
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    adicionar-colaborador: adicionar-colaborador
    atualizar-colaborador: atualizar-colaborador



management:
  endpoint:
    web:
      exposure:
        include: '*'

endereco:
  database: jdbc:postgresql://localhost:5432/gerenciador
  username: postgres
  password: 1234

